name: Keep Cron Alive

on:
  schedule:
    - cron: '0 7 1 * *'   # Her ayın 1'i 10:00 TRT
  workflow_dispatch:

permissions:
  contents: write

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - name: Update keepalive file
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ')" > .keepalive
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .keepalive
          git commit -m "chore: keepalive $(date -u +'%Y-%m-%d')" || echo "No changes"
          git push
