name: KAP Bildirim Scraper

on:
  schedule:
    - cron: '15 5 * * *'  
  workflow_dispatch:
  
jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # (pip default olarak ~/.cache/pip'i kullanıyor)

    - name: Run script
      env:
        MAIL_USER: ${{ secrets.MAIL_USER }}
        MAIL_PASS: ${{ secrets.MAIL_PASS }}
      run: python scraper.py
